version: '3.5'

services:
  postgres:
    container_name: lab-web2
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fatec}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fatec}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:

